#!/bin/bash

clear

mkdir -p csvs
mkdir -p data
mkdir -p meta

kind create cluster --config kind/config.yaml

kubectl create namespace warehouse
kubectl config set-context --current --namespace warehouse

kubectl apply -f minio/storage.yaml

helm repo add minio https://charts.min.io --force-update
helm repo update
helm install minio minio/minio -f minio/values.yaml --namespace warehouse --wait

kubectl apply -f starrocks/storage.yaml

helm repo add starrocks https://starrocks.github.io/starrocks-kubernetes-operator --force-update
helm repo update
helm install starrocks starrocks/kube-starrocks -f starrocks/values.yaml --namespace warehouse --wait

helm repo add authentik https://charts.goauthentik.io
helm repo update
helm upgrade --install authentik authentik/authentik -f authentik/values.yaml --version 2025.2.2

### HANDY COMMANDS ###
# helm uninstall starrocks -n warehouse
# kubectl exec --stdin --tty service/kube-starrocks-fe-service -- mysql -P9030 -h127.0.0.1 -u root --prompt="StarRocks > "