starrocks:
  timezone: America/Los_Angeles
  starrocksCluster:
    enabledBe: false
    enabledCn: true
  starrocksFESpec:
    replicas: 1
    storageSpec:
      name: "fe"
      existingClaim: "starrocks-pvc"
    config: |
      run_mode=shared_data
      cloud_native_storage_type=S3
      aws_s3_endpoint=minio.warehouse.svc.cluster.local:9000
      aws_s3_path=starrocks-bucket
      aws_s3_access_key=starrocks_access_key
      aws_s3_secret_key=starrocks_secret_key
      enable_load_volume_from_conf=true
      aws_s3_use_ssl=false
      aws_s3_url_protocol=http:
  starrocksCnSpec:
    replicas: 3
    config: |
      sys_log_level = INFO
      thrift_port = 9060
      webserver_port = 8040
      heartbeat_service_port = 9050
      brpc_port = 8060
      starlet_port = 9070
      storage_root_path = ${STARROCKS_HOME}/storage
    resources:
      requests:
        cpu: 1
        memory: 2Gi
  starrocksFeProxySpec:
    enabled: true
    service:
      type: NodePort
      ports:
        - name: http-port
          containerPort: 30030
          nodePort: 30030
    resources:
      requests:
        cpu: 100m
        memory: 200Mi